name: CI-CD

on:
  push:
    branches: ["main"]
  
  # Se eu quiser disparar manualmente também
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto
        # Essa action já sabe que é o repositório que ela pertence
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build e Push da Imagem Docker 
        uses: docker/build-push-action@v6
        with:
          # Caminho onde está o Dockerfile
          context: ./src
          push: true
          file: ./src/Dockerfile 
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/fake-shop:latest
            ${{ vars.DOCKERHUB_USERNAME }}/fake-shop:v${{ github.run_number }}
  
  Aprovador: 
    runs-on: ubuntu-latest 
    needs: [CI] 
    steps: 
      - name: Solicitar Revisão 
        uses: peter-evans/create-or-update-comment@v2 
        with: 
          body: | 
            @KakoF, por favor revise esta pull request.

  cd:
    runs-on: ubuntu-latest
    needs: [Aprovador]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout do projeto
        # Essa action já sabe que é o repositório que ela pertence
        uses: actions/checkout@v4
      
      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      
      - name: Configurar o Kubectl
        # Nome do cluster poderia estar em vars ou secrets
        run: aws eks update-kubeconfig --name eks-first-cluster
      
      - name: Deploy do Manifesto no Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              k8s/deployment.yaml
          images: |
              ${{ vars.DOCKERHUB_USERNAME }}/fake-shop:v${{ github.run_number }}
