name: CI-CD

on:
  push:
    branches: ["main"]
  
  # Se eu quiser disparar manualmente também
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto
        # Essa action já sabe que é o repositório que ela pertence
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construção Imagem Docker
        run: echo "Executando comando docker build"
      
      - name: Envio Imagem Docker
        run: echo "Executando comando docker push"

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando comando aws configure"
      
      - name: Configurar o Kubectl
        run: echo "Executando comando aws eks update-kubeconfig"
      
      - name: Deploy od Manifestos no Kubernetes
        run: echo "Executando comando kubectl apply"
